# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # ou la dernière version
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
